include $(TOPDIR)/rules.mk

LUCI_TITLE:=Modern router dashboard for OpenWrt
LUCI_DEPENDS:=+luci-base +rpcd
PKG_VERSION:=0.1.0
PKG_RELEASE:=2
PKG_LICENSE:=MIT
PKG_MAINTAINER:=Fovway

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature
